import { locales, type Locale } from './locales';

const en = {
  learn: 'Learn',
  tools: 'Tools',
  strategies: 'Strategies',
  skills: 'Skills',
  learnPurpose: 'Understand something',
  toolsPurpose: 'Explore an interface',
  strategiesPurpose: 'Pursue an outcome',
  skillsPurpose: 'Perform a procedure',
  learnDescription: 'Clear explanations, examples and prerequisites.',
  toolsDescription: 'Compare interfaces, permissions and limitations.',
  strategiesDescription: 'Objectives, assumptions, risks and tradeoffs.',
  skillsDescription: 'Practical steps with a result you can verify.',
  search: 'Search',
  contribute: 'Contribute',
  edit: 'Edit this page',
  helpTranslate: 'Help translate this page',
  related: 'Related knowledge',
  previous: 'Previous',
  next: 'Next',
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  advanced: 'Advanced',
  beginnerDescription: 'Start with wallets, addresses and transactions.',
  intermediateDescription:
    'Connect swaps, liquidity and lending with practical skills.',
  advancedDescription: 'Examine execution, permissions and interacting risks.',
  autoTranslate: 'Auto-translate',
  original: 'English original',
  missing:
    'This page is not available in your language yet. You are reading the English original.',
  translating: 'Translating… Your browser may download a language pack.',
  machineTranslated:
    'Machine translated. Check the English original when details matter.',
  translationUnavailable:
    'Browser translation is unavailable or failed. The English original remains available.',
  skip: 'Skip to content',
  home: 'Home',
  navigation: 'Main navigation',
  mobileNavigation: 'Mobile navigation',
  menu: 'Menu',
  language: 'Language',
  theme: 'Color theme',
  system: 'System',
  dark: 'Dark',
  light: 'Light',
  intro: 'An open group learning, building and sharing value onchain.',
  hub: 'An open knowledge hub',
  hero: 'Understand more.',
  heroAction: 'Do something useful.',
  start: 'Start here',
  join: 'Join the group',
  heroNote: 'For curious humans and capable agents.',
  openDefault: 'Open by default. Useful by contribution.',
  neutral: 'Chain neutral · Built in public',
  choosePath: 'Choose your path',
  startingPoint: 'Find your starting point',
  searchAll: 'Search all knowledge',
  exploreTopic: 'Explore a topic',
  improve: 'Found something wrong or missing? Improve this page.',
  contributionSteps:
    'Edit the Markdown, then open a pull request. Questions and suggestions are welcome in any language.',
  howContribute: 'How can I contribute?',
  principles: 'Our principles',
  principlesText:
    'Open, neutral, multichain, practical, simple, transparent and contributor friendly. Markdown holds the knowledge; GitHub records contributions. One group, many languages, shared knowledge.',
  community: 'Community links',
  agents: 'For agents',
  sharedProgress: 'Open knowledge. Shared progress.',
  markdownFirst: 'Built in public · Markdown first',
  onThisPage: 'On this page',
  updated: 'Updated',
  readTime: 'minute read',
  viewSource: 'View source',
  copy: 'Copy',
  copied: 'Copied!',
  copyManual: 'Select the text to copy it manually.',
  discussion: 'Discussion',
  discussionNote:
    'One conversation for every language. Ask questions in any language. Comments appear after this page is shared in the updates channel.',
  loadComments: 'Load Telegram comments',
  updates: 'Updates channel',
  forum: 'Community forum',
  searchKnowledge: 'Search knowledge',
  searchPlaceholder: 'Try a concept, question or #topic…',
  contentType: 'Content type',
  allPaths: 'All paths',
  browseAll: 'Browse all pages below, or search by a word or topic.',
  searching: 'Searching…',
  results: 'Results',
  noResults: 'No matching pages. Try a broader word or choose All paths.',
  searchError: 'Search could not load. Try again, or browse every page below.',
  searchNoJS: 'Text search needs JavaScript. All pages are listed below.',
  moreResults: 'Load more results',
  pages: 'pages',
  empty: 'No pages here yet.',
  notFound: "This page isn't here.",
  aiTitle: 'Learn with AI',
  aiNote:
    'Copy this context and paste it into your preferred assistant. Check important claims against the sources.',
  copyContext: 'Copy context',
  calculatorNoJS:
    'The calculator needs JavaScript. The formula and example remain readable below.',
  tryNumbers: 'Try the numbers',
  localCalculation: 'Local calculation',
  feeModel: 'Network fee model',
  gasUnits: 'Gas units',
  gasPrice: 'Gas price (gwei)',
  signatures: 'Signatures (1–12)',
  baseFee: 'Base fee per signature (lamports, 0–1,000,000,000)',
  computeLimit: 'Compute unit limit (1–1,400,000)',
  computePrice: 'CU price (micro-lamports, 0–1,000,000,000)',
  feeEstimate: 'Estimated network fee',
  feeError: 'Enter all values within the displayed limits.',
  ethFormula:
    'Gas units × gas price ÷ 1,000,000,000. Additional network fees may apply.',
  solFormula:
    'Base fee + rounded-up priority fee, converted to SOL. Account funding and program charges excluded.',
  illustration: 'Illustrative inputs, not a live quote.',
  reset: 'Reset example',
};
export type UI = Record<keyof typeof en, string>;
export const ui: Record<Locale, UI> = {
  en,
  uk: {
    learn: 'Навчання',
    tools: 'Інструменти',
    strategies: 'Стратегії',
    skills: 'Навички',
    learnPurpose: 'Зрозумій щось',
    toolsPurpose: 'Досліди інтерфейс',
    strategiesPurpose: 'Досягай мети',
    skillsPurpose: 'Виконай процедуру',
    learnDescription: 'Зрозумілі пояснення, приклади та базові знання.',
    toolsDescription: 'Порівнюйте інтерфейси, дозволи й обмеження.',
    strategiesDescription: 'Цілі, припущення, ризики й компроміси.',
    skillsDescription: 'Практичні кроки з результатом, який можна перевірити.',
    search: 'Пошук',
    contribute: 'Долучитися',
    edit: 'Редагувати сторінку',
    helpTranslate: 'Допомогти перекласти сторінку',
    related: 'Пов’язані матеріали',
    previous: 'Попередня',
    next: 'Наступна',
    beginner: 'Початковий рівень',
    intermediate: 'Середній рівень',
    advanced: 'Просунутий рівень',
    beginnerDescription: 'Почніть із гаманців, адрес і транзакцій.',
    intermediateDescription:
      'Поєднайте обміни, ліквідність і позики з практичними навичками.',
    advancedDescription: 'Досліджуйте виконання, дозволи та взаємодію ризиків.',
    autoTranslate: 'Автопереклад',
    original: 'Англійський оригінал',
    missing:
      'Ця сторінка ще не перекладена українською. Ви читаєте англійський оригінал.',
    translating: 'Перекладаємо… Браузер може завантажити мовний пакет.',
    machineTranslated:
      'Машинний переклад. Важливі деталі звіряйте з англійським оригіналом.',
    translationUnavailable:
      'Переклад у браузері недоступний або не вдався. Англійський оригінал залишається доступним.',
    skip: 'Перейти до вмісту',
    home: 'Головна',
    navigation: 'Основна навігація',
    mobileNavigation: 'Мобільна навігація',
    menu: 'Меню',
    language: 'Мова',
    theme: 'Колірна тема',
    system: 'Системна',
    dark: 'Темна',
    light: 'Світла',
    intro:
      'Відкрита спільнота, що навчається, створює та ділиться цінністю ончейн.',
    hub: 'Відкритий простір знань',
    hero: 'Розумійте більше.',
    heroAction: 'Робіть щось корисне.',
    start: 'Почніть тут',
    join: 'Приєднатися до спільноти',
    heroNote: 'Для допитливих людей і здібних агентів.',
    openDefault: 'Відкритість за замовчуванням. Користь завдяки внескам.',
    neutral: 'Незалежно від мережі · Створюємо відкрито',
    choosePath: 'Оберіть свій шлях',
    startingPoint: 'Знайдіть свою відправну точку',
    searchAll: 'Пошук серед усіх матеріалів',
    exploreTopic: 'Дослідіть тему',
    improve: 'Помітили помилку або прогалину? Покращте цю сторінку.',
    contributionSteps:
      'Змініть Markdown і відкрийте запит на злиття. Запитання та пропозиції приймаємо будь-якою мовою.',
    howContribute: 'Як долучитися?',
    principles: 'Наші принципи',
    principlesText:
      'Відкритість, нейтральність, підтримка різних мереж, практичність, простота, прозорість і зручність для учасників. Знання зберігаються в Markdown, внески — в історії GitHub. Одна спільнота, багато мов, спільні знання.',
    community: 'Посилання спільноти',
    agents: 'Для агентів',
    sharedProgress: 'Відкриті знання. Спільний поступ.',
    markdownFirst: 'Створюємо відкрито · Основа — Markdown',
    onThisPage: 'На цій сторінці',
    updated: 'Оновлено',
    readTime: 'хв читання',
    viewSource: 'Переглянути джерело',
    copy: 'Копіювати',
    copied: 'Скопійовано!',
    copyManual: 'Виділіть текст, щоб скопіювати вручну.',
    discussion: 'Обговорення',
    discussionNote:
      'Одна розмова для всіх мов. Ставте запитання будь-якою мовою. Коментарі з’являться після публікації сторінки в каналі оновлень.',
    loadComments: 'Завантажити коментарі Telegram',
    updates: 'Канал оновлень',
    forum: 'Форум спільноти',
    searchKnowledge: 'Шукати матеріали',
    searchPlaceholder: 'Введіть поняття, запитання або #тему…',
    contentType: 'Тип матеріалу',
    allPaths: 'Усі розділи',
    browseAll: 'Перегляньте всі сторінки нижче або знайдіть слово чи тему.',
    searching: 'Шукаємо…',
    results: 'Результати',
    noResults:
      'Нічого не знайдено. Спробуйте ширший запит або оберіть усі розділи.',
    searchError:
      'Не вдалося завантажити пошук. Спробуйте ще раз або перегляньте сторінки нижче.',
    searchNoJS:
      'Текстовий пошук потребує JavaScript. Усі сторінки наведено нижче.',
    moreResults: 'Більше результатів',
    pages: 'сторінок',
    empty: 'Тут ще немає сторінок.',
    notFound: 'Такої сторінки немає.',
    aiTitle: 'Навчайтеся з ШІ',
    aiNote:
      'Скопіюйте цей контекст і вставте в обраного помічника. Важливі твердження звіряйте з джерелами.',
    copyContext: 'Копіювати контекст',
    calculatorNoJS:
      'Калькулятор потребує JavaScript. Формула й приклад доступні нижче.',
    tryNumbers: 'Спробуйте числа',
    localCalculation: 'Локальний розрахунок',
    feeModel: 'Модель мережевої комісії',
    gasUnits: 'Одиниці газу',
    gasPrice: 'Ціна газу (gwei)',
    signatures: 'Підписи (1–12)',
    baseFee: 'Базова комісія за підпис (lamports, 0–1 000 000 000)',
    computeLimit: 'Ліміт обчислювальних одиниць (1–1 400 000)',
    computePrice: 'Ціна CU (micro-lamports, 0–1 000 000 000)',
    feeEstimate: 'Орієнтовна мережева комісія',
    feeError: 'Введіть усі значення в зазначених межах.',
    ethFormula:
      'Одиниці газу × ціна газу ÷ 1 000 000 000. Можливі додаткові мережеві комісії.',
    solFormula:
      'Базова комісія + округлена вгору пріоритетна комісія, у SOL. Без фінансування рахунків і зборів програм.',
    illustration: 'Прикладові значення, не поточне котирування.',
    reset: 'Скинути приклад',
  },
  es: {
    learn: 'Aprender',
    tools: 'Herramientas',
    strategies: 'Estrategias',
    skills: 'Habilidades',
    learnPurpose: 'Entiende algo',
    toolsPurpose: 'Explora una interfaz',
    strategiesPurpose: 'Persigue un objetivo',
    skillsPurpose: 'Sigue un procedimiento',
    learnDescription: 'Explicaciones claras, ejemplos y conocimientos previos.',
    toolsDescription: 'Compara interfaces, permisos y limitaciones.',
    strategiesDescription: 'Objetivos, supuestos, riesgos y compromisos.',
    skillsDescription: 'Pasos prácticos con un resultado verificable.',
    search: 'Buscar',
    contribute: 'Contribuir',
    edit: 'Editar esta página',
    helpTranslate: 'Ayuda a traducir esta página',
    related: 'Contenido relacionado',
    previous: 'Anterior',
    next: 'Siguiente',
    beginner: 'Principiante',
    intermediate: 'Intermedio',
    advanced: 'Avanzado',
    beginnerDescription: 'Empieza con carteras, direcciones y transacciones.',
    intermediateDescription:
      'Conecta intercambios, liquidez y préstamos con la práctica.',
    advancedDescription:
      'Examina la ejecución, los permisos y los riesgos combinados.',
    autoTranslate: 'Traducción automática',
    original: 'Original en inglés',
    missing:
      'Esta página aún no está disponible en español. Estás leyendo el original en inglés.',
    translating:
      'Traduciendo… El navegador puede descargar un paquete de idioma.',
    machineTranslated:
      'Traducción automática. Comprueba los detalles importantes en el original.',
    translationUnavailable:
      'La traducción del navegador no está disponible o ha fallado. El original sigue disponible.',
    skip: 'Ir al contenido',
    home: 'Inicio',
    navigation: 'Navegación principal',
    mobileNavigation: 'Navegación móvil',
    menu: 'Menú',
    language: 'Idioma',
    theme: 'Tema de color',
    system: 'Sistema',
    dark: 'Oscuro',
    light: 'Claro',
    intro: 'Un grupo abierto que aprende, construye y comparte valor onchain.',
    hub: 'Un espacio abierto de conocimiento',
    hero: 'Entiende más.',
    heroAction: 'Haz algo útil.',
    start: 'Empieza aquí',
    join: 'Únete al grupo',
    heroNote: 'Para personas curiosas y agentes capaces.',
    openDefault: 'Abierto por principio. Útil gracias a las contribuciones.',
    neutral: 'Neutral entre redes · Construido en público',
    choosePath: 'Elige tu camino',
    startingPoint: 'Encuentra tu punto de partida',
    searchAll: 'Busca en todo el contenido',
    exploreTopic: 'Explora un tema',
    improve: '¿Hay algo incorrecto o que falta? Mejora esta página.',
    contributionSteps:
      'Edita el Markdown y abre una solicitud de cambios. Aceptamos preguntas y sugerencias en cualquier idioma.',
    howContribute: '¿Cómo puedo contribuir?',
    principles: 'Nuestros principios',
    principlesText:
      'Abierto, neutral, multired, práctico, sencillo, transparente y accesible para contribuir. Markdown contiene el conocimiento; GitHub registra las contribuciones. Un grupo, muchos idiomas, conocimiento compartido.',
    community: 'Enlaces de la comunidad',
    agents: 'Para agentes',
    sharedProgress: 'Conocimiento abierto. Progreso compartido.',
    markdownFirst: 'Construido en público · Markdown primero',
    onThisPage: 'En esta página',
    updated: 'Actualizado',
    readTime: 'min de lectura',
    viewSource: 'Ver fuente',
    copy: 'Copiar',
    copied: '¡Copiado!',
    copyManual: 'Selecciona el texto para copiarlo manualmente.',
    discussion: 'Conversación',
    discussionNote:
      'Una conversación para todos los idiomas. Pregunta en cualquier idioma. Los comentarios aparecen tras compartir la página en el canal de novedades.',
    loadComments: 'Cargar comentarios de Telegram',
    updates: 'Canal de novedades',
    forum: 'Foro de la comunidad',
    searchKnowledge: 'Buscar contenido',
    searchPlaceholder: 'Prueba un concepto, pregunta o #tema…',
    contentType: 'Tipo de contenido',
    allPaths: 'Todos los caminos',
    browseAll: 'Explora todas las páginas o busca una palabra o tema.',
    searching: 'Buscando…',
    results: 'Resultados',
    noResults: 'No hay coincidencias. Prueba otra palabra o todos los caminos.',
    searchError:
      'No se pudo cargar la búsqueda. Inténtalo de nuevo o explora las páginas.',
    searchNoJS:
      'La búsqueda necesita JavaScript. Todas las páginas aparecen abajo.',
    moreResults: 'Cargar más resultados',
    pages: 'páginas',
    empty: 'Aún no hay páginas.',
    notFound: 'Esta página no existe.',
    aiTitle: 'Aprende con IA',
    aiNote:
      'Copia este contexto en tu asistente. Comprueba las afirmaciones importantes con las fuentes.',
    copyContext: 'Copiar contexto',
    calculatorNoJS:
      'La calculadora necesita JavaScript. La fórmula y el ejemplo siguen disponibles.',
    tryNumbers: 'Prueba los números',
    localCalculation: 'Cálculo local',
    feeModel: 'Modelo de comisión de red',
    gasUnits: 'Unidades de gas',
    gasPrice: 'Precio del gas (gwei)',
    signatures: 'Firmas (1–12)',
    baseFee: 'Comisión base por firma (lamports, 0–1.000.000.000)',
    computeLimit: 'Límite de unidades de cómputo (1–1.400.000)',
    computePrice: 'Precio de CU (micro-lamports, 0–1.000.000.000)',
    feeEstimate: 'Comisión de red estimada',
    feeError: 'Introduce todos los valores dentro de los límites indicados.',
    ethFormula:
      'Unidades de gas × precio del gas ÷ 1.000.000.000. Puede haber otras comisiones.',
    solFormula:
      'Comisión base + prioridad redondeada hacia arriba, en SOL. No incluye fondos para cuentas ni cargos de programas.',
    illustration: 'Valores ilustrativos, no una cotización actual.',
    reset: 'Restablecer ejemplo',
  },
  pt: {
    learn: 'Aprender',
    tools: 'Ferramentas',
    strategies: 'Estratégias',
    skills: 'Habilidades',
    learnPurpose: 'Entende algo',
    toolsPurpose: 'Explora uma interface',
    strategiesPurpose: 'Busca um resultado',
    skillsPurpose: 'Segue um procedimento',
    learnDescription: 'Explicações claras, exemplos e conhecimentos prévios.',
    toolsDescription: 'Compare interfaces, permissões e limitações.',
    strategiesDescription: 'Objetivos, premissas, riscos e escolhas.',
    skillsDescription: 'Passos práticos com um resultado verificável.',
    search: 'Pesquisar',
    contribute: 'Contribuir',
    edit: 'Editar esta página',
    helpTranslate: 'Ajude a traduzir esta página',
    related: 'Conteúdo relacionado',
    previous: 'Anterior',
    next: 'Próxima',
    beginner: 'Iniciante',
    intermediate: 'Intermediário',
    advanced: 'Avançado',
    beginnerDescription: 'Comece com carteiras, endereços e transações.',
    intermediateDescription:
      'Conecte trocas, liquidez e empréstimos à prática.',
    advancedDescription:
      'Examine a execução, as permissões e os riscos combinados.',
    autoTranslate: 'Tradução automática',
    original: 'Original em inglês',
    missing:
      'Esta página ainda não está disponível em português. Você está lendo o original em inglês.',
    translating: 'Traduzindo… O navegador pode baixar um pacote de idioma.',
    machineTranslated:
      'Tradução automática. Confira os detalhes importantes no original.',
    translationUnavailable:
      'A tradução do navegador não está disponível ou falhou. O original continua disponível.',
    skip: 'Ir para o conteúdo',
    home: 'Início',
    navigation: 'Navegação principal',
    mobileNavigation: 'Navegação móvel',
    menu: 'Menu',
    language: 'Idioma',
    theme: 'Tema de cores',
    system: 'Sistema',
    dark: 'Escuro',
    light: 'Claro',
    intro: 'Um grupo aberto que aprende, constrói e compartilha valor onchain.',
    hub: 'Um espaço aberto de conhecimento',
    hero: 'Entenda mais.',
    heroAction: 'Faça algo útil.',
    start: 'Comece aqui',
    join: 'Entre no grupo',
    heroNote: 'Para pessoas curiosas e agentes capazes.',
    openDefault: 'Aberto por princípio. Útil graças às contribuições.',
    neutral: 'Neutro entre redes · Construído em público',
    choosePath: 'Escolha seu caminho',
    startingPoint: 'Encontre seu ponto de partida',
    searchAll: 'Pesquise todo o conteúdo',
    exploreTopic: 'Explore um tema',
    improve: 'Encontrou algo errado ou faltando? Melhore esta página.',
    contributionSteps:
      'Edite o Markdown e abra um pedido de alteração. Aceitamos perguntas e sugestões em qualquer idioma.',
    howContribute: 'Como posso contribuir?',
    principles: 'Nossos princípios',
    principlesText:
      'Aberto, neutro, multirrede, prático, simples, transparente e acessível para contribuir. Markdown contém o conhecimento; GitHub registra as contribuições. Um grupo, muitos idiomas, conhecimento compartilhado.',
    community: 'Links da comunidade',
    agents: 'Para agentes',
    sharedProgress: 'Conhecimento aberto. Progresso compartilhado.',
    markdownFirst: 'Construído em público · Markdown primeiro',
    onThisPage: 'Nesta página',
    updated: 'Atualizado',
    readTime: 'min de leitura',
    viewSource: 'Ver fonte',
    copy: 'Copiar',
    copied: 'Copiado!',
    copyManual: 'Selecione o texto para copiar manualmente.',
    discussion: 'Conversa',
    discussionNote:
      'Uma conversa para todos os idiomas. Pergunte em qualquer idioma. Os comentários aparecem após a página ser compartilhada no canal de novidades.',
    loadComments: 'Carregar comentários do Telegram',
    updates: 'Canal de novidades',
    forum: 'Fórum da comunidade',
    searchKnowledge: 'Pesquisar conteúdo',
    searchPlaceholder: 'Experimente um conceito, pergunta ou #tema…',
    contentType: 'Tipo de conteúdo',
    allPaths: 'Todos os caminhos',
    browseAll: 'Explore todas as páginas ou pesquise uma palavra ou tema.',
    searching: 'Pesquisando…',
    results: 'Resultados',
    noResults: 'Nenhum resultado. Tente outra palavra ou todos os caminhos.',
    searchError:
      'Não foi possível carregar a pesquisa. Tente novamente ou explore as páginas.',
    searchNoJS:
      'A pesquisa precisa de JavaScript. Todas as páginas estão abaixo.',
    moreResults: 'Carregar mais resultados',
    pages: 'páginas',
    empty: 'Ainda não há páginas.',
    notFound: 'Esta página não existe.',
    aiTitle: 'Aprenda com IA',
    aiNote:
      'Copie este contexto no seu assistente. Confira as afirmações importantes nas fontes.',
    copyContext: 'Copiar contexto',
    calculatorNoJS:
      'A calculadora precisa de JavaScript. A fórmula e o exemplo continuam disponíveis.',
    tryNumbers: 'Experimente os números',
    localCalculation: 'Cálculo local',
    feeModel: 'Modelo de taxa de rede',
    gasUnits: 'Unidades de gas',
    gasPrice: 'Preço do gas (gwei)',
    signatures: 'Assinaturas (1–12)',
    baseFee: 'Taxa base por assinatura (lamports, 0–1.000.000.000)',
    computeLimit: 'Limite de unidades de computação (1–1.400.000)',
    computePrice: 'Preço de CU (micro-lamports, 0–1.000.000.000)',
    feeEstimate: 'Taxa de rede estimada',
    feeError: 'Insira todos os valores dentro dos limites indicados.',
    ethFormula:
      'Unidades de gas × preço do gas ÷ 1.000.000.000. Pode haver outras taxas.',
    solFormula:
      'Taxa base + prioridade arredondada para cima, em SOL. Exclui fundos para contas e cobranças de programas.',
    illustration: 'Valores ilustrativos, não uma cotação atual.',
    reset: 'Redefinir exemplo',
  },
  de: {
    learn: 'Lernen',
    tools: 'Werkzeuge',
    strategies: 'Strategien',
    skills: 'Anleitungen',
    learnPurpose: 'Verstehe etwas',
    toolsPurpose: 'Erkunde eine Oberfläche',
    strategiesPurpose: 'Verfolge ein Ziel',
    skillsPurpose: 'Führe einen Ablauf durch',
    learnDescription: 'Klare Erklärungen, Beispiele und Voraussetzungen.',
    toolsDescription: 'Oberflächen, Berechtigungen und Grenzen vergleichen.',
    strategiesDescription: 'Ziele, Annahmen, Risiken und Abwägungen.',
    skillsDescription: 'Praktische Schritte mit überprüfbarem Ergebnis.',
    search: 'Suchen',
    contribute: 'Mitmachen',
    edit: 'Diese Seite bearbeiten',
    helpTranslate: 'Diese Seite übersetzen',
    related: 'Verwandte Inhalte',
    previous: 'Zurück',
    next: 'Weiter',
    beginner: 'Einstieg',
    intermediate: 'Vertiefung',
    advanced: 'Fortgeschritten',
    beginnerDescription: 'Beginne mit Wallets, Adressen und Transaktionen.',
    intermediateDescription:
      'Verbinde Tausch, Liquidität und Kredite mit der Praxis.',
    advancedDescription:
      'Untersuche Ausführung, Berechtigungen und zusammenwirkende Risiken.',
    autoTranslate: 'Automatisch übersetzen',
    original: 'Englisches Original',
    missing:
      'Diese Seite ist noch nicht auf Deutsch verfügbar. Du liest das englische Original.',
    translating:
      'Wird übersetzt… Dein Browser lädt möglicherweise ein Sprachpaket herunter.',
    machineTranslated:
      'Maschinell übersetzt. Prüfe wichtige Details im englischen Original.',
    translationUnavailable:
      'Die Browserübersetzung ist nicht verfügbar oder fehlgeschlagen. Das Original bleibt verfügbar.',
    skip: 'Zum Inhalt springen',
    home: 'Startseite',
    navigation: 'Hauptnavigation',
    mobileNavigation: 'Mobile Navigation',
    menu: 'Menü',
    language: 'Sprache',
    theme: 'Farbschema',
    system: 'System',
    dark: 'Dunkel',
    light: 'Hell',
    intro: 'Eine offene Gruppe, die onchain lernt, entwickelt und Werte teilt.',
    hub: 'Ein offener Wissensraum',
    hero: 'Mehr verstehen.',
    heroAction: 'Etwas Nützliches tun.',
    start: 'Hier anfangen',
    join: 'Der Gruppe beitreten',
    heroNote: 'Für neugierige Menschen und fähige Agenten.',
    openDefault: 'Von Anfang an offen. Nützlich durch Beiträge.',
    neutral: 'Netzwerkneutral · Öffentlich entwickelt',
    choosePath: 'Wähle deinen Weg',
    startingPoint: 'Finde deinen Einstieg',
    searchAll: 'Alle Inhalte durchsuchen',
    exploreTopic: 'Ein Thema erkunden',
    improve: 'Etwas falsch oder unvollständig? Verbessere diese Seite.',
    contributionSteps:
      'Bearbeite das Markdown und öffne einen Pull Request. Fragen und Vorschläge sind in jeder Sprache willkommen.',
    howContribute: 'Wie kann ich mitmachen?',
    principles: 'Unsere Grundsätze',
    principlesText:
      'Offen, neutral, für mehrere Netzwerke, praktisch, einfach, transparent und zugänglich für Mitwirkende. Markdown enthält das Wissen; GitHub dokumentiert Beiträge. Eine Gruppe, viele Sprachen, gemeinsames Wissen.',
    community: 'Community-Links',
    agents: 'Für Agenten',
    sharedProgress: 'Offenes Wissen. Gemeinsamer Fortschritt.',
    markdownFirst: 'Öffentlich entwickelt · Markdown als Grundlage',
    onThisPage: 'Auf dieser Seite',
    updated: 'Aktualisiert',
    readTime: 'Min. Lesezeit',
    viewSource: 'Quelldatei ansehen',
    copy: 'Kopieren',
    copied: 'Kopiert!',
    copyManual: 'Markiere den Text, um ihn manuell zu kopieren.',
    discussion: 'Diskussion',
    discussionNote:
      'Eine Diskussion für alle Sprachen. Stelle Fragen in jeder Sprache. Kommentare erscheinen, sobald die Seite im Neuigkeitenkanal geteilt wird.',
    loadComments: 'Telegram-Kommentare laden',
    updates: 'Neuigkeitenkanal',
    forum: 'Community-Forum',
    searchKnowledge: 'Wissen durchsuchen',
    searchPlaceholder:
      'Suche nach einem Konzept, einer Frage oder einem #Thema…',
    contentType: 'Inhaltstyp',
    allPaths: 'Alle Bereiche',
    browseAll:
      'Stöbere durch alle Seiten oder suche nach einem Wort oder Thema.',
    searching: 'Suche läuft…',
    results: 'Ergebnisse',
    noResults:
      'Keine passenden Seiten. Suche allgemeiner oder wähle alle Bereiche.',
    searchError:
      'Die Suche konnte nicht geladen werden. Versuche es erneut oder nutze die Seitenliste.',
    searchNoJS:
      'Die Textsuche benötigt JavaScript. Alle Seiten sind unten aufgelistet.',
    moreResults: 'Weitere Ergebnisse laden',
    pages: 'Seiten',
    empty: 'Hier gibt es noch keine Seiten.',
    notFound: 'Diese Seite ist nicht hier.',
    aiTitle: 'Mit KI lernen',
    aiNote:
      'Kopiere diesen Kontext in deinen Assistenten. Prüfe wichtige Aussagen anhand der Quellen.',
    copyContext: 'Kontext kopieren',
    calculatorNoJS:
      'Der Rechner benötigt JavaScript. Formel und Beispiel bleiben unten lesbar.',
    tryNumbers: 'Mit Zahlen ausprobieren',
    localCalculation: 'Lokale Berechnung',
    feeModel: 'Modell der Netzwerkgebühr',
    gasUnits: 'Gas-Einheiten',
    gasPrice: 'Gaspreis (gwei)',
    signatures: 'Signaturen (1–12)',
    baseFee: 'Grundgebühr pro Signatur (Lamports, 0–1.000.000.000)',
    computeLimit: 'Limit der Recheneinheiten (1–1.400.000)',
    computePrice: 'CU-Preis (Mikro-Lamports, 0–1.000.000.000)',
    feeEstimate: 'Geschätzte Netzwerkgebühr',
    feeError: 'Gib alle Werte innerhalb der angezeigten Grenzen ein.',
    ethFormula:
      'Gas-Einheiten × Gaspreis ÷ 1.000.000.000. Weitere Netzwerkgebühren sind möglich.',
    solFormula:
      'Grundgebühr + aufgerundete Prioritätsgebühr, in SOL. Ohne Kontofinanzierung und Programmgebühren.',
    illustration: 'Beispielwerte, kein aktuelles Angebot.',
    reset: 'Beispiel zurücksetzen',
  },
};
export function validateUI() {
  const keys = Object.keys(en).sort().join(',');
  for (const locale of locales) {
    if (
      Object.keys(ui[locale]).sort().join(',') !== keys ||
      Object.values(ui[locale]).some((value) => !value.trim())
    )
      throw new Error(`Missing or unexpected UI translation keys: ${locale}`);
  }
}
